### PR TITLE
add cli script for Buie's autocontour algorithm

### PR DESCRIPTION
**Pull request by njneeteson**
As title says - had this code mostly complete lying around, tidied it up a bit and added a parser and thought it would be nice to have in the bonelab repo. There may be some kinks to work out: not totally sure all of the parameters are 100% consistent with what we now use on XCTII, or that the default thresholds are correct. Also haven't written unit tests yet.

### CODE REVIEW

**Comment by njneeteson** [comment]
CI failing due to HTTP error - retry later

**Comment by stevenkboyd** [comment]
I agree that'll be helpful to have as part of the library. The parameters for auto contour will definitely have to vary depending on image resolution/voxel size. Perhaps you could include some suggested parameters for some of our key modalities (XT1, XT2, etc).

I'm not 100% sure if there's anything more I should do with this Git process, but I'm happy if you want to merge.

Incidentally, a summer student years ago tried to implement *all* (almost) of IPL in Python. Maybe we should resurrect that some day. I think it worked quite well in the end.

**Comment by njneeteson** [comment]
That's a good point - there's a lot of hard-coded parameters currently because those were what were in the original paper, which only talks about modifying the "user input thresholds" for different specimens. Did things like the kernel sizes for medians/dilations/erosions get changed when you moved from XT1 to XT2? Perhaps more of those parameters should be moved from being hard-coded to being optional CL args.

If you remind me of the name of the most current XCTII autocontour IPL script I can go and double-check these parameters and then I can modify the parser and add suggestions of parameters for XT1 and XT2. I'm also not totally sure I got the default thresholds right for XT2 - seems like these were the values in uct_evaluate for the relevant script but I could have been looking in the wrong place.

**Comment by stevenkboyd** [comment]
Hi,

I’d use uct_evaluation and select the auto contour scripts and using “advanced” setting you can see what parameters are set. You could do that for the XT2 and it’d be a good idea to make those parameters CLI inputs, with the defaults being set to whatever we’re using in IPL.

You might log into the µCT cluster and do the same thing to see some other values for those parameters.

In general, I think it’s important to make CLI parameters possible to set without need hard coding. We can make the defaults of those parameters whatever we need, but allow people to make changes without changing the code itself. The blRapidPrototype has lots of examples of types of parameter settings.

Cheers,
Steve

--
Steven Boyd
PhD, Professor, University of Calgary
Director, McCaig Institute for Bone and Joint Health
Full Signature<https://ucalgary.ca/people/steven-boyd/contact>

On Apr 14, 2022, at 2:17 PM, Nathan Neeteson ***@***.******@***.***>> wrote:

[△EXTERNAL]




That's a good point - there's a lot of hard-coded parameters currently because those were what were in the original paper, which only talks about modifying the "user input thresholds" for different specimens. Did things like the kernel sizes for medians/dilations/erosions get changed when you moved from XT1 to XT2? Perhaps more of those parameters should be moved from being hard-coded to being optional CL args.

If you remind me of the name of the most current XCTII autocontour IPL script I can go and double-check these parameters and then I can modify the parser and add suggestions of parameters for XT1 and XT2. I'm also not totally sure I got the default thresholds right for XT2 - seems like these were the values in uct_evaluate for the relevant script but I could have been looking in the wrong place.

**Pull request merged**
