### PR TITLE
Steve/bpaq

### PR DESCRIPTION
**Pull request by stevenkboyd**
This is a utility that reads in the BPAQ questionnaire results that are stored in REDCap and calculates the BPAQ activity score. I've tested that the results are accurate and I believe this will be very useful for assessment of are datasets. It avoids using Excel, which is a nightmare.

It uses pandas dataframes. Very helpful. Unfortunately at one step I couldn't see how to do it without a for-loop, but it works. So be it.

### CODE REVIEW

**Comment by Besler** [comment]
Nice work @stevenkboyd ! I'll add a quick CLI test to make sure it runs. Do you have an example, anonymized file I can add as regression test? Make sure it produces the correct output each time.

**Comment by stevenkboyd** [comment]
Hi Bryce,

Here is an example input and output dataset. If you could add a test that uses this that would be fantastic.

Cheers,

Steve

--
Steven Boyd
PhD, Professor, University of Calgary
Director, McCaig Institute for Bone and Joint Health
Full Signature<http://people.ucalgary.ca/~skboyd/Steven_Boyd/Signature.html>

On Apr 25, 2020, at 3:18 PM, Bryce Besler <notifications@github.com<mailto:notifications@github.com>> wrote:



Nice work @stevenkboyd<https://github.com/stevenkboyd> ! I'll add a quick CLI test to make sure it runs. Do you have an example, anonymized file I can add as regression test? Make sure it produces the correct output each time.

**Comment by Besler** [comment]
@stevenkboyd Okay, tests are working!

You'll see a great number of commits here. I did this so if you want, you can thumb through each small commit and see what I changed/added and why.

I made two minor changes:
1) No '.csv' file extension addition. If the user want it as .txt, they get it as .txt
2) Formatted outputs without '\n' everywhere. More portable.

**Comment by stevenkboyd** [comment]
Great, thanks. Does this mean we can merge? Shall I?
Steve

--
Steven Boyd
PhD, Professor, University of Calgary
Director, McCaig Institute for Bone and Joint Health
Full Signature<http://people.ucalgary.ca/~skboyd/Steven_Boyd/Signature.html>

On Apr 29, 2020, at 1:09 PM, Bryce Besler <notifications@github.com<mailto:notifications@github.com>> wrote:



@stevenkboyd<https://github.com/stevenkboyd> Okay, tests are working!

You'll see a great number of commits here. I did this so if you want, you can thumb through each small commit and see what I changed/added and why.

I made two minor changes:

  1.  No '.csv' file extension addition. If the user want it as .txt, they get it as .txt
  2.  Formatted outputs without '\n' everywhere. More portable.

**Comment by Besler** [comment]
Please do!
________________________________

**Pull request merged**
