### PR TITLE
Move from xlrd to openpyxl

### PR DESCRIPTION
**Pull request by Besler**

### CODE REVIEW

**Comment by Besler** [comment]
@stevenkboyd Following up on your email here!

There was a major update to [xlrd](https://github.com/python-excel/xlrd) (1.2 -> 2.0) and they removed the ability to read `.xlsx` files. I am going to guess something legal. The project looks dead anyway and they're recommending [openpyxl](https://github.com/chronossc/openpyxl).

Anyhow, moving forwards, just do this:
```python
df = pd.read_excel(ifile, engine="openpyxl")
```
It [looks like](https://github.com/pandas-dev/pandas/issues/38424) the panda's developers will fix this upstream, but for now we can do this.

Do you mind merging this branch once you've seen it?

**Comment by Besler** [comment]
P.S. don't push to master :p

**Comment by Besler** [comment]
Last thing, you'll have to rerun `pip install -e .` on your local machine for these changes to take effect since `requirements.txt` was modified from `xlrd` to `openpyxl`.

**Comment by stevenkboyd** [comment]
Thanks, Bryce!
Steve
--
Steven Boyd
PhD, Professor, University of Calgary
Director, McCaig Institute for Bone and Joint Health
Full Signature<https://wpsites.ucalgary.ca/steven-boyd/>

On Dec 12, 2020, at 1:48 PM, Bryce Besler <notifications@github.com<mailto:notifications@github.com>> wrote:

[△EXTERNAL]




Last thing, you'll have to rerun pip install -e . on your local machine for these changes to take effect since requirements.txt was modified from xlrd to openpyxl.

**Pull request merged**
