### PR TITLE
Implement blImage2ImageSeries and blImageSeries2Image

### PR DESCRIPTION
**Pull request by Besler**
- blImage2ImageSeries
- blImageSeries2Image

### CODE REVIEW

**Comment by Besler** [comment]
@stevenkboyd Let me know if this is what you expected. If you like it, feel free to merge and delete the branch (all options on this page). If you want to try it out:
```bash
git checkout --track origin/Besler/ImageSeries
```

Here is the help for each function.
**blImage2ImageSeries**
```bash
$ blImage2ImageSeries -h
usage: blImage2ImageSeries [-h] [-e EXTENSION] [-n NUMBER_OF_DIGITS]
                           input_filename output_filename

Convert a 3D image to a series of 2D Images

Example usage:
    blImage2ImageSeries ~/.bldata/test25a.aim test25a

Output files will be overwritten if they exist. The string is
formatted by snprintf.

Care is taken to ensure the output image is of a type supported by
the file format. There may be rescaling of the image intensities
to fit inside the most appropriate data type supported by the
requested file type.

Supported extension include:
    bmp
    tif tiff
    png
    jpeg jpg

positional arguments:
  input_filename        Input image
  output_filename       Output converted image (typically .nii)

optional arguments:
  -h, --help            show this help message and exit
  -e EXTENSION, --extension EXTENSION
                        Filename extension without a period (default: bmp)"
  -n NUMBER_OF_DIGITS, --number_of_digits NUMBER_OF_DIGITS
                        Number of digits to format with (default: 4)"
```

**blImageSeries2Image**
```bash
$ blImageSeries2Image -h
usage: blImageSeries2Image [-h] [-e EXPRESSION] [-o] [-v] [-m]
                           input_directory output_filename

Convert a series of 2D images to one 3D image

Example usage:
    blImageSeries2Image ~/.bldata/dicom dicom.nii

There are a great deal of details in the DICOM standard of while not
all are handled by this function. For projects larger than, say, 10
subjects, one may want to go with a commercial DICOM importer.

Stacking of slices will be determined by an alpha-numeric sort.

positional arguments:
  input_directory       Input image
  output_filename       Output converted image (typically .nii)

optional arguments:
  -h, --help            show this help message and exit
  -e EXPRESSION, --expression EXPRESSION
                        An expression for matching files (default: *)"
  -o, --overwrite       Overwrite output without asking
  -v, --verbose         Verbose output
  -m, --multi_component
                        Set to export all components of the image. By default, only the first component is exported.
```

**Comment by Besler** [comment]
This is an issue inside vtkDICOMImageReader. Looking at [blDICOM2AIM](https://github.com/Bonelab/Bonelab-Old/tree/master/projects/Dicom2Aim) from Bonelab-Old, they actually use grassroots dicom (GDCM) to read DICOM files. GDCM is known to be much more robust against the ever complexifying DICOM standard. I looked through gdcm and [the distribution on conda ](https://github.com/conda-forge/gdcm-feedstock/blob/eb9437d6ae29ebfe37c23652b055b6249c7057fe/recipe/build.sh#L37)does not compile against VTK. Ergo, no vtkGDCMImageReader.
 
 
We have three options moving forward:
- Forget about the “off standard” formats and use commercial software at the edge cases
- I work with the conda-forge community to get GDCM building w/ VTK support
- We build our own version of GDCM and distribute it under the Numerics88 channel.

**Comment by Besler** [comment]
Discussion started here: https://github.com/conda-forge/gdcm-feedstock/issues/21

**Comment by Besler** [comment]
Based on some email discussion:
- Going to use SimpleITK instead of vtk for read/write.
- Will support DICOM but not AIM

**Comment by Besler** [comment]
@stevenkboyd Alright, transition to SimpleITK has been complete. Points of note:
- `blImage2ImageSeries` will not write a DICOM stack. If you want this functionality, we can add it, but it requires the user setting all the DICOM keys.
- `blImageSeries2Image` can read `.bldata/dicom` and the conebeam example you sent.
- Neither works with AIM data

Here are their help sections:
**blImage2ImageSeries**
```bash
$ blImage2ImageSeries -h
usage: blImage2ImageSeries [-h] [-e EXTENSION] [-n NUMBER_OF_DIGITS] [-v]
                           [--no_rescale]
                           input_filename output_filename

Convert a 3D image to a series of 2D Images

Example usage:
    blImage2ImageSeries ~/.bldata/test25a.nii temp/test25a

Output files will be numbered according to last dimension slice number
and formatted as follows:
    '{output_filename}_{number}.{extension}'
Output files will be overwritten if they exist. The method will
automatically figure out the number of digits required. However, if you
want your filenames to have a specific number of zeros greater than that
required, please set `number_of_digits`.

AIM files are not supported. It is recommended to use blImageConvert
if you would like to serialize an AIM.
    blImageConvert filename.aim filename.nii
    blImage2ImageSeries filename.nii filename

Currently, only single component images are supported. Please submit
an issue if support for Vector images is required.

Writing of DICOM series is not supported because it requires delicate
handling of the DICOM tags. Please see the SimpleITK DICOM documentation
to write your own DICOM series writer.

Writing is performed using the SimpleITK ImageSeriesWriter. Supported
extension include:
    bmp
    tif tiff
    png
    jpeg jpg

Many filetypes used for 2D images (png, bmp, jpg) only support a limited
number of data types. For this reason, the image may need to be cast to a
supporting type. By default, the algorithm will stretch the dynamic range
of the image to fit optimally inside the new type. However, if you do not
want the datatype to be stretch, set the flag `--no_rescale` to cause
direct conversion. This may cause loss of data, for example when going
from a signed to unsigned type.

positional arguments:
  input_filename        Input image
  output_filename       Output converted image prefix

optional arguments:
  -h, --help            show this help message and exit
  -e EXTENSION, --extension EXTENSION
                        Filename extension without a period (default: bmp)
  -n NUMBER_OF_DIGITS, --number_of_digits NUMBER_OF_DIGITS
                        Number of digits to format with (default: -1)
  -v, --verbose         Verbose output
  --no_rescale          Rescale pixel types on casting
```

**blImageSeries2Image**
```bash
$ blImageSeries2Image -h
usage: blImageSeries2Image [-h] [-e EXPRESSION] [-o] [-v]
                           input_directory output_filename

Convert a series of 2D images to one 3D image

Example usage:
    blImageSeries2Image ~/.bldata/dicom dicom.nii

There are a great deal of details in the DICOM standard of which not
all are handled by this function. If you experience nuanced outputs,
please consult a commercial DICOM importer.

Stacking of slices will be determined by GDCM if the input is a DICOM
series, otherwise an alpha-numeric sort.

If you are not reading in a DICOM, it is highly recommended to set a
matching expression with `-e` to avoid extra files - like .DS_store,
text files, other images - from being input into the stack. If the
script fails, this is almost always the problem. `expression` is
ignored for DICOM data.

The output cannot be an AIM type. If you require an AIM, please write
to an intermediate type (say, .nii) and then convert to AIM using
`blImageConvert`.

positional arguments:
  input_directory       Input image
  output_filename       Output converted image

optional arguments:
  -h, --help            show this help message and exit
  -e EXPRESSION, --expression EXPRESSION
                        An expression for matching files (default: *)
  -o, --overwrite       Overwrite output without asking
  -v, --verbose         Verbose output
```

**Comment by stevenkboyd** [comment]
Hi,

That’s a work of art. Impressive!

Cheers,
Steve

--
Steven Boyd
PhD, Professor, University of Calgary
Director, McCaig Institute for Bone and Joint Health
Full Signature<http://people.ucalgary.ca/~skboyd/Steven_Boyd/Signature.html>


On Jan 15, 2020, at 6:02 PM, Bryce Besler <notifications@github.com<mailto:notifications@github.com>> wrote:


@stevenkboyd<https://github.com/stevenkboyd> Alright, transition to SimpleITK has been complete. Points of note:

  *   blImage2ImageSeries will not write a DICOM stack. If you want this functionality, we can add it, but it requires the user setting all the DICOM keys.
  *   blImageSeries2Image can read .bldata/dicom and the conebeam example you sent.
  *   Neither works with AIM data

Here are their help sections:
blImage2ImageSeries

$ blImage2ImageSeries -h
usage: blImage2ImageSeries [-h] [-e EXTENSION] [-n NUMBER_OF_DIGITS] [-v]
                           [--no_rescale]
                           input_filename output_filename

Convert a 3D image to a series of 2D Images

Example usage:
    blImage2ImageSeries ~/.bldata/test25a.nii temp/test25a

Output files will be numbered according to last dimension slice number
and formatted as follows:
    '{output_filename}_{number}.{extension}'
Output files will be overwritten if they exist. The method will
automatically figure out the number of digits required. However, if you
want your filenames to have a specific number of zeros greater than that
required, please set `number_of_digits`.

AIM files are not supported. It is recommended to use blImageConvert
if you would like to serialize an AIM.
    blImageConvert filename.aim filename.nii
    blImage2ImageSeries filename.nii filename

Currently, only single component images are supported. Please submit
an issue if support for Vector images is required.

Writing of DICOM series is not supported because it requires delicate
handling of the DICOM tags. Please see the SimpleITK DICOM documentation
to write your own DICOM series writer.

Writing is performed using the SimpleITK ImageSeriesWriter. Supported
extension include:
    bmp
    tif tiff
    png
    jpeg jpg

Many filetypes used for 2D images (png, bmp, jpg) only support a limited
number of data types. For this reason, the image may need to be cast to a
supporting type. By default, the algorithm will stretch the dynamic range
of the image to fit optimally inside the new type. However, if you do not
want the datatype to be stretch, set the flag `--no_rescale` to cause
direct conversion. This may cause loss of data, for example when going
from a signed to unsigned type.

positional arguments:
  input_filename        Input image
  output_filename       Output converted image prefix

optional arguments:
  -h, --help            show this help message and exit
  -e EXTENSION, --extension EXTENSION
                        Filename extension without a period (default: bmp)
  -n NUMBER_OF_DIGITS, --number_of_digits NUMBER_OF_DIGITS
                        Number of digits to format with (default: -1)
  -v, --verbose         Verbose output
  --no_rescale          Rescale pixel types on casting

blImageSeries2Image

$ blImageSeries2Image -h
usage: blImageSeries2Image [-h] [-e EXPRESSION] [-o] [-v]
                           input_directory output_filename

Convert a series of 2D images to one 3D image

Example usage:
    blImageSeries2Image ~/.bldata/dicom dicom.nii

There are a great deal of details in the DICOM standard of which not
all are handled by this function. If you experience nuanced outputs,
please consult a commercial DICOM importer.

Stacking of slices will be determined by GDCM if the input is a DICOM
series, otherwise an alpha-numeric sort.

If you are not reading in a DICOM, it is highly recommended to set a
matching expression with `-e` to avoid extra files - like .DS_store,
text files, other images - from being input into the stack. If the
script fails, this is almost always the problem. `expression` is
ignored for DICOM data.

The output cannot be an AIM type. If you require an AIM, please write
to an intermediate type (say, .nii) and then convert to AIM using
`blImageConvert`.

positional arguments:
  input_directory       Input image
  output_filename       Output converted image

optional arguments:
  -h, --help            show this help message and exit
  -e EXPRESSION, --expression EXPRESSION
                        An expression for matching files (default: *)
  -o, --overwrite       Overwrite output without asking
  -v, --verbose         Verbose output

**Pull request merged**
